### ISSUE TITLE
DMG vs PKG?

### ISSUE THREAD

**Issue by robertritz** [The-Nicholas-R-Barrow-Company-LLC/PyMacApp#5]
First, let me say thanks for a great little package. This streamlined my bash script and makes things nice and neat. 

I'm trying to notarize my first pkg and it is taking quite a long time, if it ever works I would like to do a pull request with a few small tweaks including docs, fixing spelling, etc.

My question for you: Is it possible to make a dmg instead of a pkg?

Elsewhere I've seen it alluded that it isn't possible to make a dmg reliably with a PySide6/PyQT app. Is this right? For my case, I have a straightforward myapp.app and I simply want to drag it over if at all possible.

**Comment by barrownicholas** [comment]
@robertritz I don't have much experience with DMGs, since I've always preferred installers (PKGs). I did see that there was a tool (https://stackoverflow.com/a/76018593/14717625) that can possibly handle this. If you prefer a GUI, there is also https://www.araelium.com/dmgcanvas. I might look into [create-dmg](https://github.com/create-dmg/create-dmg) in the future, but no timeline. 

Edit: I should add that right now this uses `pkgbuild` from Apple's Developer Tools, a built-in module (assuming people follow the setup directions, which just confirms that the developer tools are installed). In theory, something like `create-dmg` is portable.

**Comment by robertritz** [comment]
Awesome thanks for the info. Would you welcome pull requests to add functionality or add documentation?

**Comment by ghost** [comment]
@robertritz yeah that would be awesome! I'm all about open-source projects and contributions so I'll happily pull as much as you want to contribute!
